# Site settings
title: Luca9527 | A Luca's Test Homepage
description: "A Luca's test homepage, built with Jekyll."
url: /
author:
  name: "The Review Index"
  email: "dyutibarma@gmail.com"
  url: "https://thereviewindex.com"

# Build settings
baseurl: /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Plugins
gems:
  - jekyll-paginate
  - jekyll-sitemap

# Custom variables
version: "1.0.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
